name: Download Test

on:
#  schedule:
#    - cron: '0 8 * * *' # Runs every day at midnight (UTC)
  workflow_dispatch:

jobs:
  download-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: sas08081.nat.sas.com
          username: mauro.cazzari
          password: It$n0tyours!
          port: 22
          source: "Code/Viya_Manager.tar.gz"
          target: /tmp
    
      # - name: Check target folder
      #   run: |
      #     if [ ! -d /Users/mauro.cazzari/Downloads ]; then
      #       ls -al /
      #       echo "Target folder not found."
      #     else
      #       echo "Target folder found."
      #       exit 1
      #     fi

      # - name: Download New CSV
      #   run: |
      #     if curl -o /Users/mauro.cazzari/Downloads/README.md https://github.com/sassoftware/iot-manage-viya-4-cloud-environments-with-viya_manager/blob/main/README.md; then
      #       echo "CSV download successful."
      #     else
      #       echo "CSV download failed."
      #       exit 1
      #     fi

      # - name: Check CSV File Size
      #   id: check-csv
      #   run: |
      #     if [ -s /Users/mauro.cazzari/Downloads/README.md ]; then
      #       echo "CSV file is not empty."
      #     else
      #       echo "CSV file is empty."
      #       exit 1
      #     fi
          
      # - name: Check for Differences
      #   id: check-differences
      #   run: |
      #     if ! diff -q data/new-data.csv data/childcare_locations.csv; then
      #       echo "CSV files are different."
      #       echo "DIFFERENT_CSV=true" >> $GITHUB_ENV
      #     else
      #       echo "CSV files are the same. Skipping commit."
      #       echo "DIFFERENT_CSV=false" >> $GITHUB_ENV
      #     fi

      # - name: Overwrite CSV
      #   if: steps.check-csv.outcome == 'success' && env.DIFFERENT_CSV == 'true'
      #   run: |
      #     mv data/new-data.csv data/childcare_locations.csv

      # - name: Commit and Push Changes
      #   if: steps.check-csv.outcome == 'success' && env.DIFFERENT_CSV == 'true'
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
          
      #     timestamp=$(date +'%Y%m%d%H%M%S')
      #     branch_name="update-csv-$timestamp"

      #     git checkout -b "$branch_name"

      #     git add data/childcare_locations.csv

      #     git commit -m "Update CSV file"

      #     git push origin "$branch_name"

      #     git checkout main
      #     git merge --no-ff "$branch_name"
      #     git push origin main

      #     # delete the temporary branch
      #     git branch -d "$branch_name"
      #     git push origin --delete "$branch_name"
